apiVersion: v1
kind: Service
metadata: 
  name: mc01
  labels: 
    app: mc01
spec:
  ports: 
  - port: 11211
    targetPort: vpromc-port
    protocol: TCP
  selector:
    app: vpromc
    type: ClusterIP