apiVersion: v1
kind: Service
metadata: 
  name: rmq01
  labels:
    app: rmq01
spec: 
  selector: 
    app: rmq01
  ports:
      - port: 15672
        targetPort: rmq01_port
        protocol: TCP
  type: ClusterIP
