apiVersion: v1
kind: Service
metadata:
  name: vproapp_service
  labels:
    app: vproapp
spec:
  ports:
  - port: 80
    targetPort: vproapp_port
    protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer
  #loadBalancerIP: 10.0.0.
 